### ISSUE TITLE
Set-Up Linting

### ISSUE THREAD

**Issue by RemLampa** [reactph/reactjsph-website#1]
ESLint + Prettier?

Anong style/coding standard i-adopt natin? :grin:

**Comment by psongpin** [comment]
https://github.com/reactph/reactjsph-website/pull/9 @RemLampa  feel free to comment change requests

**Comment by psongpin** [comment]
I used Eslint + Prettier + Airbnb. not sure if you prefer Airbnb or Standard. I just went with the most common setup. If you find strict or loose, let me know or just push straight in the PR lol.

**Comment by RemLampa** [comment]
Haha. AirBNB rin ako.

**Comment by jromest** [comment]
Closing this as per #9
