### ISSUE TITLE
Make Image Loading in Dev Board More "Graceful"

### ISSUE THREAD

**Issue by franreysaycon** [reactph/reactjsph-website#132]
Right now at (https://reactjs.org.ph/dev-board/), the images are being loaded in the default behavior of the browser of which dependent on the browser, it breaks the layout initially. Let's make this better by adding a placeholder and only show the image when it finishes loading.

**Requirements**
1. Create a ImagePlaceholder component that is a Skeleton that adjusts to the expected size of the images. I'll leave it to you what will be the color scheme of this Skeleton just make sure it's aesthetically matches the current paradigm of the design. ( Include screenshots in your pull request)
2. Create a paradigm to allow the requirement of only showing the image when it has been fully cached / downloaded by the browser. It can be a hook or a library. (better if it's a simple hook)
3. Add a simple animation (can be just a combination of ease in transition of increasing opacity) when the images are fully loaded.

**STRETCH FOR OPTIMIZATION**
1. Make the images be lazy loaded so it won't downloaded everything at once with a generous offset. (up to you)

**Comment by SandraBiros** [comment]
Hello I would like to work on this. Please assign me this issue

**Comment by jpelaa** [comment]
Hi @franreysaycon Please assign this issue to me. I'm really interested to work on this.
