### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by psongpin** [reactph/reactjsph-website#19]
Please refer to the design: https://xd.adobe.com/spec/967e129d-f3bb-4a08-6f39-553da7ddef6d-e04f/

**Comment by sid995** [comment]
I would like to fix this issue and contribute to the repo

**Comment by jromest** [comment]
Hey @sid995, thank you for expressing your interest in contributing to this project, feel free to work on this issue.

This is the header component needed to build:
![image](https://user-images.githubusercontent.com/25174423/64505665-3c374e00-d307-11e9-9790-0dec305816f7.png)

Logo will be available after this PR #23 merged.

Also, don't hesitate to ask if you have some questions.

**Comment by jromest** [comment]
@sid995, do you still want this issue to be assigned to you?

**Comment by ericsoncluciano** [comment]
if no one still doing this i can do this including the hero section let me know.
