### ISSUE TITLE
ReactJS Philippines Website Roadmap

### ISSUE THREAD

**Issue by jromest** [reactph/reactjsph-website#21]
This roadmap shows what we are currently planning to work on. This roadmap is open to change and we welcome contribution. Please see the [public project board](https://github.com/reactph/reactjsph-website/projects) for more details.

## Now
Things we are currently working on:
- Home Page

## Next
Things we will be working on in the near future:
- Blog Page
- Event/Meetup Page
- Job Boards Page

### Tech Stack
- [Gatsby](https://www.gatsbyjs.org/)
- [Rebass](https://rebassjs.org/)
- [Emotion](https://emotion.sh/docs/introduction)

### Design
[Here's the design](https://xd.adobe.com/spec/967e129d-f3bb-4a08-6f39-553da7ddef6d-e04f/) of the website.

- [x] Homepage
- [ ] Blog
- [ ] Events
- [ ] Jobs

### Structure

**Folder Structure**
```
- contents
    - blog
    - events
    - jobs
- src
    - components
    - assets
        - images
        - fonts
    - pages
    - templates
- static
```

**Content Structure**
- blog (markdown/mdx)
```
---
path: '/path'
title: 'Blog Title'
date: '<date_published>'
---
Blog contents...
```
- events
  - ~~fetch content from meetup~~
  - ~~and/or use json format for past events~~
  - fetch data from ReactJS PH Facebook page
- jobs
  - json?

**Comment by franreysaycon** [comment]
closing this. we will just revisit.
