### ISSUE TITLE
Meetups and Blog Data Source

### ISSUE THREAD

**Issue by psongpin** [reactph/reactjsph-website#31]
We need to configure the data/filesource for the Meetups and Blog to be able to feed it to the meetups section/page.

**Comment by galacemiguel** [comment]
While we have an official Meetup account now, I'd like for us to use Facebook events as our data source for the meet-ups section for two reasons:
1. We can create media posts on the Facebook event page (while Meetup will only show hyperlinks)
2. Our community is already very Facebook-centric, so I'd like to limit our members' interaction with other platforms first

Can you work on this this weekend? @psongpin

**Comment by galacemiguel** [comment]
While we have an official Meetup account now, I'd like for us to use Facebook events as our data source for the meet-ups section for two reasons:
1. We can create media posts on the Facebook event page (while Meetup will only show hyperlinks)
2. Our community is already very Facebook-centric, so I'd like to limit our members' interaction with other platforms first

Do you have time to work on this? @psongpin

**Comment by galacemiguel** [comment]
Closing in favor of https://github.com/reactph/reactjsph-website/issues/60.
