### ISSUE TITLE
Add favicon and meta tags

### ISSUE THREAD

**Issue by jromest** [reactph/reactjsph-website#43]
Favicon can be add in `gatsby-config.js` under `gatsby-plugin-manifest` and meta tags can be add in `layout.js` using `seo.js` component.

**Comment by ericsoncluciano** [comment]
Nice, I can do this today. may I know if brandmark will be the main favicon? also requesting for a photo for meta tags

**Comment by jromest** [comment]
You can use the [logo](https://github.com/reactph/reactjsph-website/blob/master/src/images/brandmark.svg) in both favicon and meta photo.
