### ISSUE TITLE
Custom 404 Page

### ISSUE THREAD

**Issue by kimberrypi** [reactph/reactjsph-website#56]
Hello 👋🏼,

You might want to customize your 404 page. Currently it's the default

```
NOT FOUND
You just hit a route that doesn't exist... the sadness.
```

**Comment by galacemiguel** [comment]
Hi, @kimberrypi! We don't have a lot of pages right now, so maybe we can just redirect to the index if they try to access an unknown route for now.

Do you mind opening a PR?

**Comment by galacemiguel** [comment]
Closed by https://github.com/reactph/reactjsph-website/pull/68.
