### ISSUE TITLE
How to get a facebook graphql token?

### ISSUE THREAD

**Issue by jisundr** [reactph/reactjsph-website#92]
Hello guys.

Can you give me some reference on how to get facebook graphql token for gatsby-source-facebook-graphql? Thanks in advance.

**Comment by franreysaycon** [comment]
https://github.com/reactph/reactjsph-website/pull/67?fbclid=IwAR02hZfNNDEo6O1dfqshGwwa2f9dNQMt9RiOiv2ToS0JjleIHH7WL-3u6qw#issue-385588218 steps are here.

**Comment by jisundr** [comment]
Got it. Thanks.
